### Nnmpy
NumPy (Numerical Python) is an open-source Python library that is widely used for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. NumPy is crucial for data analysis, machine learning, and engineering applications because it enables efficient numerical computation with Python. Here are some key features of NumPy:

- Efficient Array Storage and Processing: NumPy arrays are more efficient for storing and manipulating data than Python's built-in list structures.

- Vectorized Operations: NumPy allows you to perform operations on arrays without writing loops, which can lead to significant performance improvements.

- Broadcasting Capabilities: This feature allows NumPy to work with arrays of different shapes during arithmetic operations.

- Integrated Mathematical Functions: NumPy provides many functions that are essential for performing statistical analyses and other mathematical operations on arrays.

- Linear Algebra Operations: Tools for solving linear equations, finding eigenvalues, and matrix operations are readily available in NumPy.

- Random Number Generation: It includes capabilities to generate arrays of random numbers and perform random sampling.

Due to its performance and versatile functionality, NumPy is a foundational library for many other Python data science and machine learning libraries like SciPy, Pandas, and Scikit-learn.

### NumPy Array
In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of numpy, a powerful package to do data science.

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [3]:
# Import the numpy package as np so that you can refer to numpy with np.
import numpy as np

# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)
print(np_baseball)


# Print out type of np_baseball
print(type(np_baseball))


[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


#### Baseball players' height
You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: height_in. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

In [5]:
height_in = [74, 74, 72, 75, 75, 73] 
# Create a numpy array from height_in: np_height_in
print(height_in)

np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)


# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74, 74, 72, 75, 75, 73]
[74 74 72 75 75 73]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542]
